services:
  vllm-server:
    image: vllm/vllm-openai:v0.19.0-cu130
    container_name: vllm-qwen
    runtime: nvidia # Necesitas nvidia-container-toolkit instalado en el servidor
    ports:
      - "8000:8000"
    volumes:
      # Usamos una ruta relativa para el cache si quieres, o la del sistema
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HF_TOKEN=${HF_TOKEN}
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --model Qwen/Qwen3-0.6B
      --trust-remote-code